server:
  port: 8080
---
profiles: dev
spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/videolibrary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: hanlin
    password: pass
    ##driverClassName: org.mysql.Driver
---
profiles: prod
spring:
  jpa: