server:
  port: 8080
---
profiles: dev
spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/videoLibrary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: zipcoder
=======
    url: jdbc:mysql://localhost:3306/videolibrary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: hanlin
    password: pass
>>>>>>> 7a0cdd757ddc2c4dc89a950467892ed1973858a9
    ##driverClassName: org.mysql.Driver
---
profiles: prod
spring:
  jpa: