server:
  port: 8080
---
profiles: dev
spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql


    url: zipcodefullstack.ctneiu8xwepi.us-east-2.rds.amazonaws.com}:3306/FullStackVideo
    username: DreamTeam
    password: ZipCodeWilmington

    ##driverClassName: org.mysql.Driver
---
profiles: prod
spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: zipcodefullstack.ctneiu8xwepi.us-east-2.rds.amazonaws.com}:3306/FullStackVideo
    username: DreamTeam
    password: ZipCodeWilmington
    ##driverClassName: org.mysql.Driver
---

