server:
  port: 8080
---
profiles: dev
spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:mysql://localhost:3306/videoLibrary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: gbrad
    password: kali
    ##driverClassName: org.mysql.Driver
---
profiles: prod
spring: